before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rake db:migrate RAILS_ENV=test && bundle exec rake
gemfile:
  - Gemfile
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
env:
  - "RAILS_VERSION=4.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - rvm: ruby-head
      env: "RAILS_VERSION=master"
    - rvm: ruby-head
      env: "RAILS_VERSION=4.0"
    - rvm: ruby-head
      env: "RAILS_VERSION=3.1"
    - rvm: 2.0.0
